---
- name: MacBook Pro
  hosts: localhost

  vars:
    user_dir: "{{ lookup('env', 'HOME') }}"

  roles:
    - { role: common, tags: ['common'] }
    - { role: ssh, tags: ['ssh', 'dot'] }
    - { role: dotfiles, tags: ['dotfiles', 'dot'] }
    - { role: neovim, tags: ['neovim', 'dot'] }
    - { role: tmux, tags: ['tmux', 'dot'] }
    - { role: packages, tags: ['packages'] }
    - { role: cleanup, tags: ['cleanup'], when: "cleanup | default(false) | bool" }

  tasks:
    # Commented Homebrew sections remain in place
    # - name: Brew - Formulae
    #   community.general.homebrew:
    #     update_homebrew: yes
    #     state: present
    #     name:
    #       - amazon-ecs-cli
    #       - antigen
    #       - awscli
    #       - coreutils
    #       - fasd
    #       - git
    #       - gnu-sed
    #       - htop
    #       - make
    #       - neovim
    #       - powerlevel9k
    #       - shellcheck
    #       - terraform
    #       - tig
    #       - tmux
    #       - tree
    #       - vagrant
    #       - wget
    #   tags:
    #     - brew

    # - name: Brew - Casks
    #   community.general.homebrew_cask:
    #     state: installed
    #     accept_external_apps: True
    #     sudo_password: "{{ unix_password }}"
    #     name:
    #       - adobe-acrobat-reader
    #       - atom
    #       - caffeine
    #       - docker
    #       - google-chrome
    #       - iterm2
    #       - lastpass
    #       - microsoft-edge
    #       - slack
    #       - spectacle
    #       - spotify
    #       - vlc
    #   tags:
    #     - brew

    # - name: Python - Packages
    #   ansible.builtin.pip:
    #     name: "{{ item }}"
    #     executable: "{{ pip_executable }}"
    #   with_items:
    #     - ansible
    #     - neovim
    #     - ranger-fm
    #     - yq
    #     - jq
