---
- name: MacBook Pro Configuration
  hosts: macbooks
  gather_facts: true

  roles:
    - { role: common, tags: ['common'] }
    - { role: ssh, tags: ['ssh', 'dot'] }
    - { role: dotfiles, tags: ['dotfiles', 'dot'] }
    - { role: neovim, tags: ['neovim', 'dot'] }
    - { role: tmux, tags: ['tmux', 'dot'] }
    - { role: packages, tags: ['packages'] }
    - { role: cleanup, tags: ['cleanup'], when: "cleanup | default(false) | bool" }
