---
- name: Brew - Formulae
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - bat
    - buildkit
    - certbot
    - direnv
    - docker-compose
    - go
    - goreleaser/tap/goreleaser
    - htop
    - jq
    - pre-commit
    - pv
    - py3cairo
    - pygobject3
    - pyqt5
    - python
    - rename
    - rlwrap
    - shellcheck
    - starship
    - syncthing
    - telnet
    - tmux
    - tree
    - vim
    - wget
    - yq
  tags:
    - brew

- name: Brew - Casks
  community.general.homebrew_cask:
    name: chromedriver
    state: present
  tags:
    - brew

- name: Python - Packages
  ansible.builtin.pip:
    name:
      - ansible-core
      - cryptography
      - PyYAML
      - awscli
      - awsume
      - boto3
      - cfn-lint
      - pre-commit
      - prompt_toolkit
      - pynvim
  tags:
    - python
