---
- name: .aliases - Config file
  ansible.builtin.file:
    src: "{{ user_dir }}/Projects/macbook-pro/host_files/{{ inventory_hostname }}/aliases"
    dest: "{{ user_dir }}/.aliases"
    owner: "{{ ansible_user_uid | quote }}"
    group: "{{ ansible_user_gid | quote }}"
    state: link
  tags:
    - dot

- name: pyrightconfig - Config file
  ansible.builtin.file:
    src: "{{ user_dir }}/Projects/macbook-pro/host_files/{{ inventory_hostname }}/pyrightconfig.json"
    dest: "{{ user_dir }}/pyrightconfig.json"
    owner: "{{ ansible_user_uid | quote }}"
    group: "{{ ansible_user_gid | quote }}"
    state: link
  tags:
    - dot

- name: .env_vars - Config file
  no_log: True
  ansible.builtin.template:
    src: "env_vars.j2"
    dest: "{{ user_dir }}/.env_vars"
    owner: "{{ ansible_user_uid | quote }}"
    group: "{{ ansible_user_gid | quote }}"
    mode: '0600'
  tags:
    - dot

- name: .zshrc - Config file
  ansible.builtin.template:
    src: "zshrc.j2"
    dest: "{{ user_dir }}/.zshrc"
    owner: "{{ ansible_user_uid | quote }}"
    group: "{{ ansible_user_gid | quote }}"
    mode: '0644'
  tags:
    - dot

- name: .functions - Config file
  ansible.builtin.file:
    src: "{{ user_dir }}/Projects/macbook-pro/host_files/{{ inventory_hostname }}/functions"
    dest: "{{ user_dir }}/.functions"
    owner: "{{ ansible_user_uid | quote }}"
    group: "{{ ansible_user_gid | quote }}"
    state: link
  tags:
    - dot 