---
- name: Cleanup files and directories
  ansible.builtin.file:
    state: absent
    path: "{{ user_dir }}/{{ item }}"
  loop:
    - .ssh/id_rsa
    - .ssh/id_ed25519
    - .ssh/id_rsa.pub
    - .ssh/id_ed25519.pub
    - .ssh/config
    - .vault_pass.txt
    - .aliases
    - pyrightconfig.json
    - .env_vars
    - .zshrc
    - .functions
    - .tmux.conf
    - .tmux.conf.local
    - .config/nvim
  tags:
    - cleanup

- name: Cleanup directories if empty
  ansible.builtin.file:
    state: absent
    path: "{{ user_dir }}/{{ item }}"
  loop:
    - .ssh
    - .config
  tags:
    - cleanup 