---
- name: SSH - Private keys
  ansible.builtin.copy:
    src: "{{ host_files_dir }}/{{ item }}"
    dest: "{{ ssh_dir }}/{{ item }}"
    owner: "{{ ansible_user_uid | quote }}"
    group: "{{ ansible_user_gid | quote }}"
    mode: '0600'
  with_items: "{{ ssh_keys }}"

- name: SSH - Public keys
  ansible.builtin.copy:
    src: "{{ host_files_dir }}/{{ item }}.pub"
    dest: "{{ ssh_dir }}/{{ item }}.pub"
    owner: "{{ ansible_user_uid | quote }}"
    group: "{{ ansible_user_gid | quote }}"
    mode: '0644'
  with_items: "{{ ssh_keys }}"

- name: SSH - Config file
  ansible.builtin.template:
    src: "config.j2"
    dest: "{{ config_paths.ssh_config }}"
    owner: "{{ ansible_user_uid | quote }}"
    group: "{{ ansible_user_gid | quote }}"
    mode: '0644'
  tags:
    - dot

- name: Ansible Vault - Password file
  no_log: False
  ansible.builtin.file:
    src: "{{ host_files_dir }}/vault_pass.txt"
    dest: "{{ user_dir }}/.vault_pass.txt"
    owner: "{{ ansible_user_uid | quote }}"
    group: "{{ ansible_user_gid | quote }}"
    state: link
  tags:
    - dot 