---
- name: TMUX - Config file
  ansible.builtin.copy:
    src: "host_files/{{ inventory_hostname }}/{{ item }}"
    dest: "{{ user_dir }}/.{{ item }}"
    owner: "{{ ansible_user_uid | quote }}"
    group: "{{ ansible_user_gid | quote }}"
    mode: '0644'
  with_items:
    - tmux.conf
    - tmux.conf.local
  tags:
    - dot 