---
- name: Create needed directories in home directory
  ansible.builtin.file:
    state: directory
    path: "{{ user_dir }}/{{ item }}"
    owner: "{{ ansible_user_uid | quote }}"
    group: "{{ ansible_user_gid | quote }}"
    mode: '0700'
    modification_time: preserve
    access_time: preserve
  with_items:
    - .ssh
    - .config 